# ===================================================================
# ekf_gps.yaml - Dual EKF Configuration
# ===================================================================

### 1. Local EKF (Odom Frame) ###
ekf_filter_node_local:   # <--- ต้องชื่อนี้เป๊ะๆ ให้ตรงกับ Launch File
  ros__parameters:
    frequency: 30.0
    two_d_mode: true
    publish_acceleration: false
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom    # Local ยึด Odom เป็นหลัก

    # Wheel Odometry
    odom0: /odom
    odom0_config: [false, false, false,
                   false, false, false,
                   true,  true,  false,
                   false, false, true,
                   false, false, false]
    odom0_queue_size: 10
    odom0_differential: false

    # IMU
    imu0: /imu
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  true,  true,  true,
                  true,  true,  true]
    imu0_remove_gravitational_acceleration: true


### 2. Global EKF (Map Frame) ###
ekf_filter_node_global:  # <--- ต้องชื่อนี้เป๊ะๆ
  ros__parameters:
    frequency: 30.0
    two_d_mode: true
    publish_acceleration: false
    publish_tf: true     # ตัวนี้จะเป็นคนปล่อย map -> odom
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: map     # Global ยึด Map เป็นหลัก

    # Inputs เหมือน Local (Odom + IMU)
    odom0: /odom
    odom0_config: [false, false, false,
                   false, false, false,
                   true,  true,  false,
                   false, false, true,
                   false, false, false]
    odom0_queue_size: 10

    imu0: /imu
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  true,  true,  true,
                  true,  true,  true]
    imu0_remove_gravitational_acceleration: true

    # GPS Input (จาก Navsat Transform)
    odom1: /odometry/gps
    odom1_config: [true,  true,  false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom1_queue_size: 10
    odom1_differential: false