initialize_origin:
  ros__parameters:
    local_xy_frame: "map"
    local_xy_origin: "my_farm"  
    local_xy_origins:
      - name: "my_farm"
        latitude: 15.772145
        longitude: 104.202322
        altitude: 0.0
        heading: 0.0